# this is a simple ansible playbook for installing packages needed by blivet
# test suite
# you can this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'

---
- hosts: all
  vars:
    python: python3

  become: true

  tasks:
  - name: Install common test dependencies
    package: name={{item}} state=installed
    with_items:
      - anaconda-core
      - dosfstools
      - e2fsprogs
      - xfsprogs
      - hfsplus-tools
      - zanata-python-client

  - name: Install Python 3 test dependencies
    package: name={{item}} state=installed
    with_items:
      - python3-mock
      - python3-coverage
      - python3-pocketlint
      - python3-bugzilla
      - python3-pep8
      - python3-six
      - python3-kickstart
      - python3-pyudev
      - python3-pyparted
      - libselinux-python3
      - python3-blockdev
      - python3-bytesize
    when: python == "python3"

  - name: Install Python 2 test dependencies (Fedora)
    package: name={{item}} state=installed
    with_items:
      - python2-mock
      - python2-coverage
      - python2-pocketlint
      - python2-bugzilla
      - python-pep8
      - python2-six
      - pykickstart
      - python2-pyudev
      - pyparted
      - libselinux-python
      - python2-blockdev
      - python-bytesize
    when: python == "python2" and ansible_distribution == "Fedora"

  - name: Install Python 2 test dependencies (CentOS)
    package: name={{item}} state=installed
    with_items:
      - python-mock
      - python-coverage
      - python-pocketlint
      - python-bugzilla
      - python-pep8
      - python-six
      - pykickstart
      - python-pyudev
      - pyparted
      - libselinux-python
      - python-blockdev
      - python-bytesize
    when: python == "python2" and ansible_distribution == "CentOS"
